#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

mapFields -consistent -sourceTime "latestTime" -parallelSource -parallelTarget ../10mps6000rpmPre/

runApplication pyFoamPlotRunner.py mpirun -np 6 $(getApplication) -parallel

runApplication reconstructPar

paraFoam
#------------------------------------------------------------------------------
