#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication snappyHexMesh -overwrite

runApplication renumberMesh -overwrite
# Create faceZones for baffles and fan
runApplication topoSet

# Create wall and cyclic baffles and the fields on them
runApplication createBaffles -overwrite

gunzip 0/pointLevel.gz

lines=$(sed -n '$=' 0/pointLevel)

lines=$(($lines-3))

sed -i "${lines} i\    cyclicFaces_master\n    {\n        type            cyclic;\n    }\n    cyclicFaces_slave\n    {\n        type            cyclic;\n    }" 0/pointLevel

runApplication decomposePar

runApplication mpirun -np 6 $(getApplication) -parallel

runApplication reconstructPar
#------------------------------------------------------------------------------
